version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: postqre_qtutor
      POSTGRES_USER: skorw
      POSTGRES_PASSWORD: 123321
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis_container
    ports:
      - "6379:6379"

volumes:
  postgres_data:
