# Generated by Django 5.0.6 on 2024-07-03 14:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
                ('difficult', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, help_text='Уровень сложности')),
                ('language', models.CharField(blank=True, help_text='Язык категории', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название темы', max_length=100)),
                ('difficult', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, help_text='Уровень сложности')),
                ('text', ckeditor.fields.RichTextField(help_text='Текст темы')),
                ('image', models.ImageField(blank=True, help_text='Изображение для темы', upload_to='main/img/')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата создания темы', null=True)),
                ('category', models.ForeignKey(help_text='Категория', on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
